apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
    env: dev
spec:
  type: NodePort
  selector:
    app: nginx
    env: dev
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: monitoring
    port: 9100
    targetPort: 9100
    nodePort: 30100
